README.md
charts/px/README.md
charts/px/templates/hooks/pre-install/etcd-preinstall-hook.yaml

Validates the ETCD url endpoint before installing the chart.
This helps ensuring there isnt a misconfigured etcd which is a requirement for Portworx. 
Closes #13 

ETCD validation before chart install.

---

charts/px/templates/hooks/post-delete/px-postdelete-unlabelnode.yaml
charts/px/templates/hooks/pre-delete/px-predelete-nodelabel.yaml
charts/px/templates/hooks/pre-install/etcd-preinstall-hook.yaml

Makes the pre and post install / delete hook names as unique. 
the hook name contains the Release Name which is a built in object of helm thus making it unique unless specified externally by the user. 
Closes #16 
@harsh-px The Hook name is unique and will not interfere with the error stating that the pre-install hook already exists.

Unique Pre-install hook name for the release.

---

charts/portworx/README.md
charts/portworx/templates/portworx-ds.yaml

Detect if the environment is IKS, and if yes, then use unused drives that have a filesystem on it
Closes # https://portworx.atlassian.net/browse/PWX-6569

use filesystemDrives if deploying in IKS

---

charts/portworx/templates/portworx-ds.yaml

Required for px-1.7, and CRI/containerd support
We forgot to add an additional mount for Portworx 1.7 CRI/containerd support.
Closes # PWX-6783

PWX-6783: containerd volume fix

---

charts/portworx/templates/portworx-rbac-config.yaml

helm chart install fails if the namespace already exists.

Remove creation of portworx namespace 

---

charts/portworx/templates/portworx-rbac-config.yaml

1. We cannot create portworx namespace in the helm chart, as the helm chart installation fails
if the namespace already exists.
2. If the `portworx` namespace does not exist we cannot create the px-role for that namespace.
The installation process for PX + IBM Key Protect would be like this
1. Create portworx namespace
2. Create the px-role and the role bindings for a non-existent service account (px-account) -> k8s does not complain on this
3. Create the px-ibm k8s secret
4. Install the helm chart
With this flow, PX when installed will automatically get authenticated with IBM KP.
Closes #

Remove portworx namespace creation and px-role from helm chart

---

charts/portworx/templates/portworx-ds.yaml

* fixing helm-chart mounts (adding journalmount* for internal log-proxy, also fixing PKS)
* adding annotations to capture install-vars (useful for upgrades when helm-home lost)
Signed-off-by: Zoran Rajic <zox@portworx.com>
Helm had mount-points discrepancy compared to install.portworx.com
Also, will be very useful to capture install-vars as ds/portworx annotations  (not perfect, but enough to be able to manually reconstruct the install/upgrade).
-

Fixing mounts and adding install annotations

---

charts/portworx/templates/portworx-ds.yaml

On kubernetes > 1.10 the mountPath with `:shared` renders an `Invalid volume specification`. This rendered the chart unusable on kubernetes > v1.10.
To make it work
Closes #74 
I won't add my real-name. This is simple enough to get it through like it is right now. I do agree to the DCO.

fix(portworx-ds): remove :shared

---

charts/portworx/templates/hooks/pre-install/etcd-preinstall-hook.yaml
charts/portworx/templates/portworx-ds.yaml
docker-images/preinstall-hook/etcdStatus.sh

Signed off by : @mrshah-at-ibm
This PR adds capability to deploy the helm chart with an etcd that has self-signed certs but does not require client auth
Closes https://github.com/portworx/helm/issues/71

Fix deployment for optional client-auth for etcd

---

charts/portworx/templates/portworx-lighthouse.yaml

Signed-off-by: Paul <paul@portworx.com>
In 2.0 we added stork-connector and px-central to lighthouse.
This requires the lighthouse pod to be able to list cluster objects.
For this we had to change to a ClusterRole and Binding.
I also added the parameter required to tell lighthouse we're running on kubernetes. 
This is so lighthouse knows it should ask for kubeConfigs so we can do migrations.
Closes #PWX-7940

PWX-7940: Change LH Role to a ClusterRole and Binding to a ClusterBinding. Also fix the permissions for stork api's

---

charts/portworx/templates/portworx-controller.yaml

Signed-off-by: Sathya Balakrishnan <sathya@portworx.com>
This fixes a rendering issue with helm
```Error: render error in "portworx/templates/portworx-controller.yaml": template: portworx/templates/portworx-controller.yaml:94:13: executing "portworx/templates/portworx-controller.yaml" at <not>: wrong number of args for not: want 1 got 2```
Closes #

fix helm rendering error

---

charts/portworx/README.md
charts/portworx/templates/portworx-controller.yaml
charts/portworx/templates/portworx-ds.yaml
charts/portworx/values.yaml

To support AKS installations
Closes #PSG-98
updated oci-mon to v2.1.2 since 2.0.3.6 did not have azure support

PSG-98: Add azure env vars from secret for AKS installations

---

charts/portworx/templates/hooks/post-delete/px-postdelete-unlabelnode.yaml
charts/portworx/templates/hooks/pre-delete/px-predelete-nodelabel.yaml

with https://hub.docker.com/r/bitnami/kubectl
Solving the issue 
```
helm chart tries to install lachlanlevonson/k8s-kubectl image which does not exist
```
Closes #9625

PWX-9625: replaced the current kubectl repo

---

charts/portworx/values.yaml

Signed-off-by: Paul <paul@portworx.com>
Bump lighthouse version and dependend packages to 2.0.5

Bump lighthouse versions to 2.0.5

---

charts/portworx/templates/portworx-controller.yaml
charts/portworx/templates/portworx-csi.yaml
charts/portworx/templates/portworx-ds.yaml
charts/portworx/templates/portworx-lighthouse.yaml
charts/portworx/templates/portworx-monitor.yaml
charts/portworx/templates/portworx-storageclasses.yaml
charts/portworx/templates/portworx-stork.yaml

This is needed to have helm install work on Kubernetes 1.16
PSG-134

PSG-134 Switch apiVersion to apps/v1 for DaemonSet and Deployment

---

charts/portworx/templates/portworx-stork.yaml

Warning  FailedScheduling  119s (x29 over 12m)  stork  Post http://stork-service.kube-system.svc.cluster.local:8099/filter: dial tcp: lookup stork-service.kube-system.svc.cluster.local on 10.0.220.2:53: no such host

Remove full FQDN to avoid custom cluster name

---

charts/portworx/templates/portworx-service.yaml

px-sdk needs to be on port 9020.   This matches what is generated by the spec generator

PWX-11024 px-sdk needs to be on port 9020

---

charts/portworx/templates/portworx-controller.yaml
charts/portworx/templates/portworx-csi.yaml
charts/portworx/templates/portworx-ds.yaml
charts/portworx/templates/portworx-lighthouse.yaml
charts/portworx/templates/portworx-stork.yaml

When the chart is deployed to a cluster that contains nodes with taints, some of the deployments fail for not having the necessary `tolerations` statement.
This PR passes the `tolerations` value through to all the templates that have a `nodeSelector` statement.

Fix tolerations

---

charts/portworx/templates/_helpers.tpl
charts/portworx/templates/portworx-controller.yaml
charts/portworx/templates/portworx-csi.yaml
charts/portworx/templates/portworx-ds.yaml
charts/portworx/templates/portworx-lighthouse.yaml
charts/portworx/templates/portworx-stork.yaml
charts/portworx/values.yaml

Introduced a new value requirePxEnabledTag. 
When set to true, portworx workloads will only install across nodes when px/enabled: true label is set on node. 
This feature is useful in eks/autoscaling environments where you want to stop portworx from automatically rolling out to newly provisioned nodes (where the node count is higher than 3). Without this behaviour, portworx DS will always try and install across all available nodes even though the  cluster limit is dependant on license restrictions.

Added option to require px/enabled label on hosts.

---

charts/portworx/templates/portworx-controller.yaml

Portworx-controller unable to list and watch configmap
Closes #174 

add watch/list configmap permissions for portworx-controller

---

charts/portworx/files/portworx-cluster-dashboard.json
charts/portworx/files/portworx-etcd-dashboard.json
charts/portworx/files/portworx-node-dashboard.json
charts/portworx/files/portworx-volume-dashboard.json
charts/portworx/templates/portworx-controller.yaml
charts/portworx/templates/portworx-csi.yaml
charts/portworx/templates/portworx-ds.yaml
charts/portworx/templates/portworx-lighthouse.yaml
charts/portworx/templates/portworx-monitor.yaml
charts/portworx/templates/portworx-stork.yaml

This PR fixes 2 issues:
1. Update monitoring template to match latest generated by Portworx spec generator, more specifically updated Prometheus version to run on latest k8s releases and updated latest Grafana dashboards
2. Changed template to use `prefix` AND instead of `infix` so it can deployed with helm version 3 (this is because of GO 1.14 templates)
Closes #158

Updating monitoring templates and fixes for helm 3 (infix

---

charts/portworx/templates/portworx-controller.yaml

This PR adds the missing "persistentvolume-expander" controller to portworx-pvc-controller deployment definition.
This brings the Helm chart inline with yaml generated by PX Central.
Without this in place, Portworx volumes are unable to be expanded from the PVC request definition; you get the following error when describing the PVC if you try:
Error expanding volume "my-namespace-name/my-pvc-name" of plugin "kubernetes.io/portworx-volume": Get http://x.x.x.x:9001/v1/osd-volumes/versions: dial tcp x.x.x.x:9001: i/o timeout
This change fixes that.

Add missing persistentvolume-expander

---

charts/portworx/templates/portworx-ds.yaml
charts/portworx/values.yaml

This PR adds a new optional parameter to specify a dedicated kvdb device when using internal KVDB: kvdbDevice.
This was a requirement from Mavenir as they are using helm to deploy Portworx and wants to specify a dedicated kvdb device for the internal KVDB.
Closes #
**Special notes for your reviewer**: 
I tested this in on-prem and EKS clusters.

Adding option to specify dedicated kvdb device

---

charts/px-backup/templates/px-central-oidc/pxcentral-keycloak.yaml

Signed off: Diptiranjan
This fix is required for cases where creating /.keycloak directory is failing.

Mounting empty directory for /.keycloak

---

charts/px-backup/templates/px-central-oidc/pxcentral-keycloak.yaml

Signed off - Diptiranjan
Fix for failing stateful set deployment because the name is not standard to DNS-1123 label naming format.

Changing the keycloakDir var name to lower case to avoid the deployment error.

---

charts/px-backup/templates/px-backup/pxcentral-etcd.yaml

Signed off - Diptiranjan
Lowering the memory usage will prevent the pod from getting exited with OOM.

Tune in ETCD_SNAPSHOT_COUNT to 10000 for lower memory usage.

---

px-central/templates/px-lighthouse/px-central-ui/pxcentral-ui.yaml
px-central/templates/px-lighthouse/px-monitor-svc.yaml
px-central/values.yaml

Signed off : Diptiranjan
Default values are as follows 
px-backup-ui - LoadBalancer
pxcentral-grafana - NodePort
pxcentral-cortex-nginx - NodePort

helm param to make px-backup-ui, pxcentral-grafana and pxcentral-cortex-nginx service configurable with different service type.

---

charts/px-license-server/templates/license-server-ha-setup.yaml
charts/px-monitor/templates/cortex/cortex-sts.yaml
charts/px-monitor/templates/prometheus/prometheus.yaml
charts/px-monitor/templates/px-monitor-post-install-setup.yaml

What this PR does / why we need it: When installed by torpedo, Role, RoleBinding and StatefulSet without namespace will be created in default namespace
Which issue(s) this PR fixes (optional)
Closes #
Special notes for your reviewer: verified by local torpedo test run

[OC-589] Add missing namespaces for license server and monitor charts

---

px-central/templates/px-lighthouse/pxcentral-post-install-hook.yaml
px-central/templates/px-monitor/grafana/grafana-config.yaml
px-central/values.yaml

Signed-off by: Diptiranjan
Removed the helm key for setting the oidc-client-secret during px-monitor install.

[OC-673] : oidc-client-secret to be detected automatically for grafana config during px-monitor install.

---

px-central/templates/px-backup/pxcentral-backup.yaml
px-central/templates/px-backup/pxcentral-mongodb.yaml
px-central/values.yaml

Signed-off By: Diptiranjan
1. Installs of mongodb with 3 replicasets.
2. Both etcd and mongodb sts will be present and the default will be mongodb.
Tests:
1. Installation with px-backup enabled and created backups on a cluster.
2. Pod delete and verifying data.
3. Scaling down to 0 replicas and scale up to 3.

[PB-1118]: Changes for using mongodb as datastore for px-backup.

---

px-central/templates/px-backup/pxcentral-backup.yaml
px-central/values.yaml
single_chart_migration/migration.sh

Added following changes to support mongo migration settings
- Added update permission for configMap
- Added mongo-migration-status configMap to store the status of mongo migration
N.A
This PR is need to support mongo migration feature in px-backup

Added following changes to support mongo migration settings

---

px-central/templates/px-backup/pxcentral-backup.yaml
px-central/values.yaml
single_chart_migration/migration.sh

Removed the mongo-migration-status configmap as currently, it will be stored in a mongo document.
- Changed the default value of mongomigration to complete
- Also overwritten the default value of mongomigration to incomplete in migrations.sh,
as it will do helm upgrade.

Removed the mongo-migration-status configmap as currently, it will be stored in a mongo document.

---

single_chart_migration/migration.sh
single_chart_migration/mongo.yaml

Added --mongo-trail-migration option.
- As part of --mongo-trail-migration option, following steps will be executed.
- Will deploy the temporary mongo deploy
- Will being down the px-backup, to avoid updates to the etcd datastore.
- Will execute migrationctl tool to migrate the objects from etcd to mongoDB.
- As part of migrationctl, we will dump a report which will contain details
about all the objects that are migrated.
- Delete the temporary mongo deployment.
Added migrationctl and mongo.yaml files
**Testing:**
```
[root@central-stump-ninja-3 single_chart_migration]# ./migration.sh --namespace px-backup --helmrepo /root/helm --mongo-trail-migration
release namespace = px-backup
helm repo name = /root/helm
mongotrailmigration set true …
```

Added --mongo-trail-migration option.

---

px-central/README.md
px-central/templates/px-lighthouse/px-central-ui/pxcentral-ui.yaml
px-central/values.yaml
single_chart_migration/README.md
single_chart_migration/migration.sh

px-central-ui service will also be going to remain.
Signed-off By: Diptiranjan
Test:
1. Fresh Install 
kubectl get svc -n px-backup
NAME                                     TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)               AGE
px-backup                                ClusterIP      10.233.48.4     <none>        10002/TCP,10001/TCP   33m
px-backup-ui                             LoadBalancer   10.233.24.153   <pending>     80:30917/TCP          33m
px-central-ui                            LoadBalancer   10.233.17.237   <pending>     80:30170/TCP          33m
pxc-backup-mongodb-headless              ClusterIP      None            <none>        27017/TCP             33m
pxcentral-apiserver                      ClusterIP      10.233.55.176   <none>        10005/TCP,10006/TCP …

[OC-748]: Retaining px-backup-ui for smooth upgrade experience.

---

single_chart_migration/migration.sh

post-install-job tag to be 2.0.0 for rolling back after failure with migration.

---

charts/px-central/templates/NOTES.txt

This PR is a cherry-pick of `Namespace fix for helm install prompt`
Changes are in master, cherry-picking to `2.1.0`
Closes # https://portworx.atlassian.net/browse/OC-1046

[CHERRY-PICK] fixed OC-1046: wrong namespace shown, updated to release namespace

---

single_chart_migration/migration.sh

signed-off-by: Diptiranjan
Even if px-backup is not enabled, migration script should work and move the existing px-license-server and px-monitor to the px-central release.
Closes # OC-1082
Test results have been updated in OC-1082.

[OC-1082]: migration script to work even if px-backup is disabled and for external ls server.

---

single_chart_migration/migration.sh

signed-off-by: Diptiranjan
Deleting prometheus resource linked with old px-monitor chart to get upgraded with px-central chart.
Closes # OC-1152
*Test*
Successfully upgraded from 1.2.3 to 2.1.2 and no more prometheus pod crash is seen.
Results have been updated in OC-1152.

[OC-1152]: Need to delete the previous prometheus resource for its upgrading during migration.

---

versions.yaml

kopiaexecutor needs to be 1.2.0.

---

charts/portworx/crds/core_v1_storagecluster_crd.yaml
charts/portworx/crds/core_v1_storagenode_crd.yaml
charts/portworx/templates/hooks/pre-upgrade/retain-daemonset-install.yaml
charts/portworx/templates/storage-cluster.yaml
charts/portworx/values.yaml

Create template to generate StorageCluster based on helm parameters.
- StorageCluster is only created by helm for fresh install
- If daemonset presents, then helm will not create StorageCluster, operator will create it afterwards
- External kvdb and cluster token are not supported yet, tracked by these two tickets:
[OPERATOR-727](https://portworx.atlassian.net/browse/OPERATOR-727) 
[OPERATOR-728](https://portworx.atlassian.net/browse/OPERATOR-728)
- There are some unsupported scenarios for operator generated StorageCluster: such as cloud provider detection and secret provider. we may want to let helm create storageCluster for migration
[OPERATOR-730](https://portworx.atlassian.net/browse/OPERATOR-730)

create template for StorageCluster spec

---

charts/portworx/templates/_helpers.tpl
charts/portworx/templates/storage-cluster.yaml
charts/portworx/values.yaml

The existing helm chart assumed that the kvdb certs are present in a specific
directory. With operator we want to mount the kvdb certs/creds via a
secret. Kept the existing model to support existing customer migrating from
daemonset, while adding an option to specify kvdb auth secret.
Signed-off-by: Piyush Nimbalkar <pnimbalkar@purestorage.com>
Closes #

Support secure kvdb with operator

---

charts/portworx/templates/hooks/post-install/px-create-cluster-token.yaml
charts/portworx/templates/portworx-k8s-secrets.yaml
charts/portworx/templates/storage-cluster.yaml

Signed-off-by: Piyush Nimbalkar <pnimbalkar@purestorage.com>
This will work for existing daemonset installs as well as new installs. But we ideally want new customers to use the same namespace as StorageCluster to store their secrets. 
And eventually we should just change the default px installation namespace to portworx. This is what we are going to do on spec generator. So, for now, I am keeping `portworx` as the default namespace for secrets, the way it was for daemonset.
Closes # https://portworx.atlassian.net/browse/OPERATOR-728

Support smooth migration from daemonset wrt encrypted volumes

---

charts/portworx/Chart.yaml
charts/portworx/templates/storage-cluster.yaml

1. chart.yaml needs apiVersion, otherwise "helm lint" will complain: [ERROR] Chart.yaml: apiVersion is required. The value must be either "v1" or "v2" ( legacy issue on ds chart too)
2. fix csi cannot be disabled
3. add support for journalDevice
4. fix migration-approved annotation not added

fix several issues

---

charts/px-central/templates/px-backup/pxcentral-mongodb.yaml

Signed-off-by: Diptiranjan
Need to handle the case where pods other than pod-0 can become primary too.
Closes # PB-3485
**Test**:
Details have been updated in PB-3485.

PB-3485: mongodb setup scripts to handle existing primary pod.

---

charts/portworx/Chart.yaml

Fixing k8s version issue when k8s version has `-` in the version string
**NOTE:** Also bumping up minimum k8s version to 1.21
Before
```
$ helm upgrade --debug --kubeconfig kubeconfig portworx-test helm/charts/portworx/ --dry-run
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: kubeconfig
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: kubeconfig
upgrade.go:150: [debug] preparing upgrade for portworx-test
Error: UPGRADE FAILED: chart requires kubeVersion: >=1.21.0 which is incompatible with Kubernetes v1.27.4-eks-2d98532
helm.go:84: [debug] chart requires kubeVersion: >=1.21.0 which is incompatible with Kubernetes v1.27.4-eks-2d98532
```
After
```
$ helm upgrade --debug --kubeconfig kubeconfig portworx-test …
```

PWX-31983 Fixing k8s version issue

---

charts/px-central/templates/px-backup/pxcentral-backup.yaml

During receiver creation for alert manager a CR is created from px-backup 'alertmanagerconfig' which later gets picked up by alert manager to add the receivers to it's list. 
**This PR is CRUD role permissions required for the same in px-backup**

PB-4403 | New role required alert manager config for px backup

---

charts/px-central/templates/px-backup/pxcentral-backup.yaml

For pb-4876 task, Logs from backup sync job pod is added to px-backup logs for debugging in scenarios of Job succeed, job failed, or pod not running
**Which issue(s) this PR fixes** 
[https://portworx.atlassian.net/browse/PB-4876](PB-4876)

PB-4876: Log resource permission for px-backup

---

charts/px-central/templates/px-backup/pxcentral-alertmanager.yaml
charts/px-central/templates/px-backup/pxcentral-prometheus.yaml
charts/px-central/values.yaml

**What this PR does / why we need it**: This PR has the changes to use latest images for prometheus/alertmanager and support for having basic auth
Closes # https://portworx.atlassian.net/browse/PB-5064

PB-5064: Updated prometheus/alertmanager with latest images and to support basic auth

---

charts/portworx/crds/core_v1_storagecluster_crd.yaml
charts/portworx/crds/core_v1_storagenode_crd.yaml

**What this PR does / why we need it**: Currently the CRD of storagecluster used in helm chart install is different from what the operator installs. This causes an issue when the CRD created by operator is overwritten by the CRD in helm. The mismatch in Status.Conditions fields between the 2 causes operator to continue appending status to the stc increasing its size infinitely. After updating the helm CRD, this issue will not be faced.
Closes # PWX-35781
**Testing notes**:
This includes the steps to reproduce the issue as well as fix it
1. Deploy operator and stc 
2. Update the crd of `storageclusters.core.libopenstorage.org` with the [older CRD](https://github.com/portworx/helm/blob/master/charts/portworx/crds/core_v1_storagecluster_crd.yaml) …

PWX-35781 : Updating storagecluster crd to same as operator v23.10.5

---

charts/portworx/templates/storage-cluster.yaml
charts/portworx/values.yaml
test/portworx/storagecluster_helm_template_test.go
test/portworx/testValues/storagecluster_custom_metadata.yaml
test/portworx/testValues/storagecluster_portworx_container_resources.yaml
test/portworx/testValues/storagecluster_security_disabled.yaml
test/portworx/testValues/storagecluster_security_enabled.yaml
test/portworx/testspec/storagecluster_custom_metadata.yaml
test/portworx/testspec/storagecluster_featureGates.yaml
test/portworx/testspec/storagecluster_portworx_container_resources.yaml
test/portworx/testspec/storagecluster_runtimeOptions.yaml
test/portworx/testspec/storagecluster_security_enabled.yaml
test/utils/test_utils.go

This will following fields in the storageClusterSpec
```yaml
runtimeOptions:       map[string]string              
featureGates:     map[string]string                  
metadata:
annotation: object
labels: object
security: 
enabled: bool                    
auth:
guestAccess: string            
selfSigned:                      
tokenLifetime:  string
issuer: string                     
sharedSecret:  string
```
Closes #https://purestorage.atlassian.net/browse/PWX-37682

PWX-37682 | Add missing field for StorageCluster Spec in helm

---

charts/portworx/templates/storage-cluster.yaml
charts/portworx/values.yaml
test/portworx/storagecluster_helm_template_test.go
test/portworx/testValues/storagecluster_updatestrategy_rollingupdate.yaml
test/portworx/testspec/storagecluster_updatestrategy_invalid_type.yaml
test/portworx/testspec/storagecluster_updatestrategy_ondelete.yaml
test/portworx/testspec/storagecluster_updatestrategy_rollingupdate.yaml

Added missing fields for updateStrategy component in storageCluster template
Closes #https://purestorage.atlassian.net/browse/PWX-37570

PWX-37570 | Add missing fields for updateStrategy

---

charts/px-central/templates/px-lighthouse/px-central-ui/pxcentral-ui-configmap.yaml

Moving the hard-coded API_TIMEOUT value for UI to config-map
Closes # PB-7469
Tested from UI that the config map value is correctly picked up.

PB-7469 | Moving hard-coded API_TIMEOUT value for UI to config-map

---

charts/px-central/local_snapshot_restore.py

```
pb-8928: added check for isBackupReady_for_PXDLocalSnapshotRestore flag from backup object json
```
Closes # pb-8928
Test result:
```
[core@pwx-ocp-0-167-9wcvn-worker-0-8xfxw ~]$ python3 ./test.py backup.json
2025-01-27 13:46:56,398 - ERROR - Localsnapshot restore is not possible as isBackupReady_for_PXDLocalSnapshotRestore is not set to True in the given backup json file.
[core@pwx-ocp-0-167-9wcvn-worker-0-8xfxw ~]$ vi backup.json
[core@pwx-ocp-0-167-9wcvn-worker-0-8xfxw ~]$ python3 ./test.py backup.json
+-------+-----------+------------+------------------------------------------+--------------------+
| Index | Namespace | PVC        | Name …
```

pb-8928: added check for isBackupReady_for_PXDLocalSnapshotRestore flag from backup object json

---

versions.yaml

mongodb5 image was not present in versions.yaml but is used in values.yaml, hence, air-gapped upgrade was failing.

Add mongodb5 to versions list

---

charts/px-central/templates/px-backup/pxcentral-backup.yaml

Removing datastoreEndpoints param from px-backup deployment spec
This is needed for password customisation. We are now allowing customer to provide the password and in order to escape special characters we are constructing the datastore endpoint (which is nothing but the mongodb URI) in px-backup instead of passing it as a parameter in the spec.
Closes #

Removing datastoreEndpoints param from px-backup deployment spec

---

charts/portworx/templates/portworx-operator.yaml
charts/portworx/templates/storage-cluster.yaml
charts/portworx/values.yaml
test/portworx/testValues/storagecluster_monitoring.yaml
test/portworx/testspec/storagecluster_monitoring.yaml

This PR adds support for specifying `imagePullSecrets` in the Portworx Operator deployment, which is necessary when pulling images from private registries.
It also fixes an issue where the Prometheus pod failed to start when `securityContext.runAsNonRoot` was set to true in `values.yaml`. Previously, the chart only allowed setting `runAsNonRoot`, but didn't provide a way to specify other necessary fields like `runAsUser`. This caused the Prometheus pod to crash due to insufficient security context configuration.
With this fix, users can now define a full `securityContext` block in `values.yaml`, including `runAsUser` and other relevant fields, ensuring that Prometheus starts successfully when running as a non-root user.
**Which issue(s) this PR …

PWX-43196 | PWX-43220 | Add imagePullSecret in operator deployment and Fix security context issue

---

charts/px-central/templates/px-backup/pxcentral-mongodb.yaml

This PR improves the resilience of MongoDB replica set initialization and joining in the PX-Backup Helm deployment. It addresses issues where deleting MongoDB pods one-by-one could cause the primary to become non-writable (`isWritablePrimary: false`) due to DNS propagation delays or replica set misconfiguration.
Key improvements:
- Adds a DNS wait loop to ensure all replica set peers are resolvable before MongoDB starts.
- Updates `setup.sh` to prevent secondaries from initiating a new replica set by mistake.
- Explicitly sets `MONGODB_INITIAL_PRIMARY_HOST` for all secondary pods to join `pod-0`.
- Ensures fallback conditions for clean PVC or startup cases still lead to proper replica set joining.
- Improves logging and diagnostic clarity to help …

PB-3481: Fix MongoDB replica set stability by waiting for DNS and enforcing consistent replica set join logic

---

charts/px-central/templates/px-backup/pre-install-hook/pre-install-check.yaml
charts/px-central/templates/px-backup/pre-rollback-hook/pre-rollback-check.yaml
charts/px-central/templates/px-backup/pre-upgrade-hook/pre-upgrade-check.yaml
charts/px-central/templates/px-backup/pxcentral-alertmanager.yaml
charts/px-central/templates/px-backup/pxcentral-backup.yaml
charts/px-central/templates/px-backup/pxcentral-mongodb.yaml
charts/px-central/templates/px-backup/pxcentral-prometheus.yaml
charts/px-central/templates/px-license-server/deployment.yaml
charts/px-central/templates/px-lighthouse/px-central-oidc/pxcentral-keycloak.yaml
charts/px-central/templates/px-lighthouse/px-central-ui/pxcentral-lighthouse.yaml
charts/px-central/templates/px-lighthouse/px-central-ui/pxcentral-ui.yaml
charts/px-central/templates/px-lighthouse/pxcentral-api-server.yaml
charts/px-central/templates/px-lighthouse/pxcentral-post-install-hook.yaml
charts/px-central/templates/px-monitor/cortex/cortex-backend.yaml
charts/px-central/templates/px-monitor/cortex/cortex-sts.yaml
charts/px-central/templates/px-monitor/cortex/cortex.yaml
charts/px-central/templates/px-monitor/grafana/grafana.yaml
charts/px-central/templates/px-monitor/prometheus/prometheus.yaml
charts/px-central/values.yaml

**What this PR does / why we need it**: Added global parameter for setting repo and registry to all the images
Precedence :
if images.registry is set , it will be used . Else it will fall back to the image specific registry
if images.repo is set , it will be used . Else it will fall back to the image specific repo
Closes # https://purestorage.atlassian.net/browse/PB-11135

PB-11135: Added global parameter for setting repo and registry to all the images

---

charts/px-central/templates/px-lighthouse/px-central-ui/pxcentral-lighthouse.yaml
charts/px-central/templates/px-lighthouse/px-central-ui/pxcentral-ui-configmap.yaml
charts/px-central/values.yaml

This PR adds support for platform RBAC-based namespace filtering in PX-Central UI.
- Added new configuration option `usePlatformRbac` to `pxbackup` section in values.yaml (defaults to `false`)
- Updated PX-Central Lighthouse deployment template to conditionally set `USE_PLATFORM_RBAC` environment variable
- When enabled, this allows the Lighthouse UI to leverage platform RBAC for namespace-level access control
The feature can be enabled by setting:
```yaml
pxbackup:
usePlatformRbac: true
Dummy Helm command to set the usePlatformRbac flag to true:
`helm upgrade --install px-central ./charts/px-central \
--set pxbackup.enabled=true \
--set pxbackup.usePlatformRbac=true `

PB-12057: Add platform(Rancher) RBAC support for namespace filtering in PXB
