- charts/px/templates/portworx-ds.yaml
- charts/px/templates/portworx-stork.yaml
Spec changes for Stork to for kubernetes v1.9.x
Also, includes a draft fix for #19
Closes #18 
> Stork spec changes for kubernetes version 1.9

- charts/px/templates/portworx-ds.yaml
- charts/px/templates/portworx-stork.yaml
The predicate was corrected after verifying with @disrani-px . 
This has been verified on 1.9.3 and 1.8.0 clusters
Closes #18 
> Stork spec changes for Kubernetes v 1.9.x 

- charts/portworx/templates/portworx-stork.yaml
> Fix Kubernetes version check for stork policy

- charts/portworx/templates/hooks/post-delete/px-postdelete-unlabelnode.yaml
- charts/portworx/templates/hooks/pre-delete/px-predelete-nodelabel.yaml
- charts/portworx/templates/hooks/pre-install/etcd-preinstall-hook.yaml
- charts/portworx/templates/hooks/pre-install/preinstall-cleanPreviousJobs.yaml
> Custom Registry for docker images in Helm hooks

- charts/portworx/templates/_helpers.tpl
- charts/portworx/templates/hooks/post-delete/px-postdelete-unlabelnode.yaml
- charts/portworx/templates/hooks/pre-delete/px-predelete-nodelabel.yaml
- charts/portworx/templates/hooks/pre-install/etcd-preinstall-hook.yaml
- charts/portworx/templates/hooks/pre-install/preinstall-cleanPreviousJobs.yaml
- charts/portworx/templates/portworx-ds.yaml
- charts/portworx/templates/portworx-stork.yaml
- Updates the stork role and cluster-role binding permissions. 
- Fix for semantic version comparison
Closes #25 #30 
> Update Role permissions for Stork and Semver compare for k8s versions

- charts/portworx/templates/portworx-ds.yaml
- charts/portworx/values.yaml
Need to deploy on Master node for POC environments.
Closes #
> Allow deployment on Master node for POC only

- charts/portworx/README.md
- charts/portworx/templates/hooks/pre-install/etcd-preinstall-hook.yaml
- charts/portworx/templates/portworx-ds.yaml
- charts/portworx/values.yaml
- docker-images/preinstall-hook/Dockerfile
- docker-images/preinstall-hook/etcdStatus.sh
Fixes the issue with multiple etcd urls. Draft implementation of secure ETCD pre install validation 
Closes #
> Fixes for multiple etcd urls.

- charts/portworx/README.md
- charts/portworx/values.yaml
> Fix typo in README.md

- charts/portworx/values.yaml
> imageVersion to 1.4.2,  storkVersion to 1.1.3

- charts/portworx/templates/_helpers.tpl
- charts/portworx/templates/portworx-controller.yaml
- charts/portworx/templates/portworx-csi.yaml
- charts/portworx/templates/portworx-ds.yaml
- charts/portworx/templates/portworx-stork.yaml
- charts/portworx/values.yaml
Fixes the GKE install which requires the PVC Controller. 
Fixes the Internal KVDB check, where it allows for an empty etcdEndPoint when internalKVDB is set to true
Closes #46 
> Fixes for GKE install and Internal KVDB conditional check

- charts/portworx/templates/portworx-ds.yaml
Summary of fixes:
* making px/enabled constraint apply always
* simplifying expressions -- 'if not (eq ..' into 'if ne'
* making `-a` and `-A` params mutually exclusive
* introducing optional generic `misc` parameter, that will be split and added "as is" to YAML-params (required for testing)
* stripping trailing whitespace
Closes #51 
> Fixing px/enabled constraint, and misc

- charts/portworx/values.yaml
> update image to 1.5.0

- charts/portworx/Chart.yaml
- charts/portworx/README.md
Signed-off-by: Harsh Desai <harsh@portworx.com>
Closes #
> Enfore tiller version 2.9 and above

- charts/portworx/templates/portworx-storageclasses.yaml
- charts/portworx/values.yaml
> Add storage classes; Bump PX to 1.6.0;  Bump Stork to 1.1.4

- charts/portworx/README.md
- charts/portworx/templates/portworx-ds.yaml
> Fix drive parsing

- charts/portworx/templates/portworx-rbac-config.yaml
> Revert "Remove creation of portworx namespace "

- charts/portworx/templates/portworx-ds.yaml
Signed-off-by: Harsh Desai <harsh@portworx.com>
**What this PR does / why we need it**: This fixes the issue @hrish1kesh saw yesterday on systems with selinux enabled.
Closes #
> Always mount host proc directly

- charts/portworx/templates/portworx-lighthouse.yaml
- charts/portworx/templates/portworx-service.yaml
- charts/portworx/templates/portworx-stork.yaml
- charts/portworx/values.yaml
Signed off by : @hrishipx 
Update the latest versions of Portworx. 
Closes #72 
> Bump up the Image versions after new release

- charts/portworx/templates/hooks/pre-install/etcd-preinstall-hook.yaml
> Updated the preinstall hook to use the portworx image

- charts/portworx/templates/portworx-lighthouse.yaml
Signed off by : @hrishipx 
Lighthouse needs additional RBAC permissions to run. 
Closes #76 
> Fix required Lighthouse RBAC permissions

- docker-images/preinstall-hook/etcdStatus.sh
Signed off by : @mrshah-at-ibm
This PR fixes a syntax error in etcdStatus.sh
Closes #79 
Can you please verify this by running a helm install? Thank you for the review
> Fixing syntax in shell script

- charts/portworx/templates/hooks/pre-install/etcd-preinstall-hook.yaml
Fixes #81
Signed-off-by: Harsh Desai <harsh@portworx.com>
Closes #
> Pass etcd cert and key file args only if they are present

- charts/portworx/files/portworx-cluster-dashboard.json
- charts/portworx/files/portworx-etcd-dashboard.json
- charts/portworx/files/portworx-node-dashboard.json
- charts/portworx/files/portworx-volume-dashboard.json
- charts/portworx/templates/portworx-lighthouse.yaml
- charts/portworx/templates/portworx-monitor.yaml
- charts/portworx/values.yaml
Signed-off-by: Paul <paul@portworx.com>
Moves the helm charts to the latest versions.
Adds monitoring if desired.
We're currently a bit behind on versions and we didn't have monitoring present yet.
Rancher and IKS are even further behind.
> Update to latest releases and specs

- charts/portworx/README.md
> Update and removed the old docker parameter in README.md

- charts/portworx/templates/_helpers.tpl
>  Updated and removed the extra / from the lighthouse image path 

- charts/portworx/templates/portworx-ds.yaml
- charts/portworx/values.yaml
> Added toleration values.yaml

- charts/portworx/templates/portworx-ds.yaml
>  Removed space in the toleration tag

- charts/portworx/values.yaml
Updated versions for all chart components
> Updated versions for all chart components

- charts/portworx/templates/hooks/post-delete/px-postdelete-unlabelnode.yaml
- charts/portworx/templates/hooks/pre-delete/px-predelete-nodelabel.yaml
This reverts commit 568407d6263f51551263aea3eba41025c4891a1e.
Closes #
> Revert "PWX-9625: replaced the current repo with https://hub.docker.com/r/bitnami/kubectl

- charts/portworx/values.yaml
> stork version update

- charts/portworx/values.yaml
updated stork and lighthouse versions to 2.2 versions
Closes #
> updated stork and lighthouse versions to 2.2 versions

- charts/portworx/README.md
- charts/portworx/values.yaml
Updated px version to the latest 2.2.0.5
Closes #
> updated px version to 2.2.0.5

- charts/portworx/templates/portworx-stork.yaml
- charts/portworx/values.yaml
* Remove full FQDN to avoid custom cluster name
* update px image to 2.3.2 version
Closes #
> updated px version to 2.3.2

- charts/portworx/templates/portworx-stork.yaml
PodDisruptionBudget enable for stork so Admin cannot make stork to be offline with kubctl commands
> Add PDB for stork and stork-scheduler

- charts/portworx/templates/portworx-rbac-config.yaml
- charts/portworx/templates/portworx-stork.yaml
- charts/portworx/values.yaml
> upgrade px to 2.4.0

- charts/portworx/README.md
* Added steps to install in IKS
* Added steps to upgrading the PX install via `helm upgrade`
* Note this document just lists commands using `helm 2`
Signed-off-by: Tapas Sharma <tapas@portworx.com>
Closes #
> PD-412 Add helm upgrade steps

- charts/portworx/templates/_helpers.tpl
- charts/portworx/templates/portworx-ds.yaml
- charts/portworx/templates/portworx-service.yaml
- charts/portworx/values.yaml
added portworx-api service
Closes #
> upgrade px to 2.5.1

- charts/px-backup/README.md
Signed-off-by: Tushar Raut tushar@portworx.com
> Update advanced configuration option in README.md

- charts/portworx/templates/_helpers.tpl
> changed the k8s registry url for certain k8s versions

- charts/px-backup/README.md
Signed-off-by: Tushar Raut tushar@portworx.com
> Added workaround to resolve etcd cluster issue

- charts/portworx/templates/_helpers.tpl
add compatibility with helm2 
Closes #
> changed the k8s registry url for certain k8s versions (helm2 compatibility)

- charts/px-backup/templates/px-backup/pxcentral-etcd.yaml
- charts/px-backup/values.yaml
> Fixed etcd cluster install and upgrade issue

- charts/px-backup/templates/px-backup/pxcentral-etcd.yaml
ETCD snapshotter does not work with CSI and it always needs storage class which support shared volume creation.
Reverted ETCD template to not use snapshotter.
> Reverted etcd template

- charts/px-backup/templates/px-central-ui/pxcentral-ui.yaml
Signed off: Diptiranjan
Fixing the redirection URI for /auth after session timeout.
> Setting proper rediction uri for /auth.

- px-central/templates/px-monitor/grafana/grafana.yaml
This PR is for fixing the ssl support for grafana with custom certs.
> grafana deployment to have support for ssl.

- single_chart_migration/README.md
- single_chart_migration/migration.sh
Signed off : Diptiranjan
migration.sh will be used for upgrading from multi charts (1.2.*) to single chart (1.3.0).
The script has all the steps automated to do the helm upgrade.
> Migration script to single chart upgrade.

- px-central/templates/NOTES.txt
- px-central/templates/px-lighthouse/px-central-ui/pxcentral-ui.yaml
- px-central/values.yaml
- single_chart_migration/migration.sh
Post-install Notes has been changed with respect to px-central
and with status of each component as per the values provided.
Signed-off by:  Diptiranjan
> px-backup-ui service has been renamed to px-central-ui.

- single_chart_migration/migration.sh
> [OC-696]: Figuring out release name for each component with better filtering

- single_chart_migration/migration.sh
> [OC-695] Deleting old stale post install jobs of px-monitor and px-licenseserver if present after upgrade.

- single_chart_migration/migration.sh
Added rollbackup option in migration.sh script.
- By default rollbackup option will not be set
- rollback need to set, when the mongo migration failed and
decision was made to rollback to the older version that has kvdb support.
**Testing:**
**1) Installed 1.2.2 version of px-central with px-backup.**
```
helm install px-backup portworx/px-backup --namespace px-backup --version 1.2.2 --create-namespace --set persistentStorage.enabled=true,persistentStorage.storageClassName=mysql-sc
```
```
[root@central-stump-ninja-3 ~]# kubectl get deploy -n px-backup -o yaml | grep image:
image: docker.io/portworx/px-backup:1.2.2
image: docker.io/portworx/pxcentral-onprem-api:1.2.1
image: docker.io/portworx/pxcentral-onprem-ui-backend:1.2.2
image: …
```
> Added rollbackup option in migration.sh script.

- single_chart_migration/migration.sh
PB-1306: Corrected the issues in extracting storageclass and ready replica values.
- Also updated the latest migrationctl tool.
**Testing:**
```
[root@central-stump-ninja-3 single_chart_migration]# ./migration.sh --namespace px-backup  --helmrepo /root/helm --mongo-trial-migration
release namespace = px-backup
helm repo name = /root/helm
mongotrialmigration set true
mongotrialmigration case
using storage class for mongo mysql-sc
serviceaccount/pxc-backup-mongodb-trial created
secret/pxc-backup-mongodb-trial created
configmap/pxc-backup-mongodb-trial-scripts created
service/pxc-backup-mongodb-trial-headless created
statefulset.apps/pxc-backup-mongodb-trial created
Waiting for mongoDB to be in running state
mongodb datastore is not ready yet
mongodb …
```
> PB-1306: Corrected the issues in extracting storageclass and ready replica values.

- single_chart_migration/migration.sh
Signed-off-by: Diptiranjan
Tests:
Upgrade to 2.0.1/2.0.0 support in migration script from 1.2.x .
> [OC-996]: migration.sh changes for 2.0.1 upgrade.

- single_chart_migration/migration.sh
Add support to migrate to 2.0.2
Closes # OC-1080
Have tested the fix and the migration when through:
```
release namespace = px-backup
helm repo name = /root/helm/charts/
admin user password = admin
Step-1 : Looking for enabled features
Error from server (NotFound): deployments.apps "pxcentral-cortex-distributor" not found
Error from server (NotFound): deployments.apps "pxcentral-license-server" not found
pxbackup: true, pxmonitor: false, pxlicenseserver: false
Step-2 : Searching the installed helm releases for the components
pxbackup release: px-central, pxmonitor release: , pxlicenseserver release: 
verifying if release px-central exists in namespace px-backup
Step-3 …
```
> OC-1080: Add support to migrate to 2.0.2

- charts/portworx/templates/_helpers.tpl
- charts/portworx/templates/portworx-stork.yaml
Signed-off-by: dahuang <dahuang@purestorage.com>
Closes #
> PWX-21861 Update comparing logic in stork for consistency

- charts/px-central/templates/NOTES.txt
wrong namespace shown, updated to release namespace
Closes # https://portworx.atlassian.net/browse/OC-1046
> fixed OC-1046: wrong namespace shown, updated to release namespace

- single_chart_migration/migration.sh
signed-off-by: Diptiranjan
Closes # OC-1099
Test
```
Unsupported version:
[root@ip-70-0-55-157 helm]# single_chart_migration/migration.sh --namespace px-backup  --helmrepo charts --admin-password Password1 --upgrade-version 2.0.2
release namespace = px-backup
helm repo name = charts
admin user password = Password1
upgrade version = 2.0.2
upgrade-version can only be 2.0.0 2.0.1 2.1.1
Usage: single_chart_migration/migration.sh --namespace <namespace> --helmrepo <helm repo name> --admin-password <current password of admin> --kubeconfig <kubeconfig file name>
--namespace <namespace> namespace in which px-central charts are installed
--helmrepo <helm repo name for px-central components> helm repo name , can get …
```
> [OC-1099]: Supporting 2.1.1 as a supported migration version in migration script from 1.2.x .

- charts/portworx/values.yaml
Bump PX version to 2.8.1.2
Closes #
Note: Should I update the files in stable?
> PWX-22148 update helm px version

- charts/portworx/values.yaml
Signed-off-by: dahuang <dahuang@purestorage.com>
Update px version to 2.9.1.4
Closes # PWX-23472
Tested deployment locally.
> PWX-23472-update px version to 2.1.9.4

- charts/px-central/README.md
Signed-off-by: Kesavan Thiruvenkadasamy <kthiruvenkadasamy@purestorage.com>
**What this PR does / why we need it**: Update px-central readme on helm parameters.  
Closes #
> Update px-central readme

- charts/portworx/templates/storage-cluster.yaml
> parse drives for storage and cloudStorage

- charts/portworx/templates/_helpers.tpl
> fix version parser bug when k8s version is v1.22.9-eks-810597c

- charts/portworx/templates/_helpers.tpl
> fix version parser issue

- charts/portworx/Chart.yaml
- charts/portworx/values.yaml
> change version and remove unused values

- charts/portworx/templates/_helpers.tpl
- charts/portworx/templates/storage-cluster.yaml
- charts/portworx/values.yaml
- generic env variables
- generic volumes
- generic stork volumes
- stork arguments
- max storage nodes per zone
- kvdb device for cloud storage
- misc args
- disable operator deployed storage classes
- service type for portworx services managed by operator
Signed-off-by: Piyush Nimbalkar <pnimbalkar@purestorage.com>
Closes #
> Add new parameters to the modify the storage cluster spec

- charts/portworx/templates/hooks/pre-delete/delete-storagecluster.yaml
- charts/portworx/templates/storage-cluster.yaml
Closes #
https://portworx.atlassian.net/browse/OPERATOR-839
https://portworx.atlassian.net/browse/OPERATOR-840
>  Fix stork args and ignore cluster deletion failure if not present

- charts/portworx/templates/storage-cluster.yaml
Signed-off-by: Piyush Nimbalkar <pnimbalkar@purestorage.com>
Closes # https://portworx.atlassian.net/browse/PWX-26014
> PWX-26014 Do not populate the kvdb auth secret if set as none

- charts/portworx/README.md
> add migration in readme

- charts/px-central/README.md
Signed-off-by: Kesavan Thiruvenkadasamy <kthiruvenkadasamy@purestorage.com>
Closes #
> Updated px-central readme

- versions.yaml
Signed-off-by: Kesavan Thiruvenkadasamy <kthiruvenkadasamy@purestorage.com>
Closes #
> Updated pxcentral version tag

- charts/portworx/templates/portworx-csi.yaml
- charts/portworx/templates/portworx-rbac-config.yaml
> PWX-27612 Remove Pod Security Policy from Portworx Generic helm chart.

- versions.yaml
> Modified kopia executor image tag

- charts/portworx/Chart.yaml
- charts/portworx/templates/portworx-operator.yaml
- charts/portworx/templates/storage-cluster.yaml
- charts/portworx/values.yaml
1. Update version to 2.13.0
2. Update operator to 1.10.4
3. Remove PSP
4. Add telemetry flag
Closes #
> PWX-29460 Add flag for telemetry

- charts/portworx/templates/storage-cluster.yaml
- charts/portworx/values.yaml
> [PWX-29299] Added support for OKE

- stable/index.yaml
Signed-Off-By: Diptiranjan
Fixing repo url in master to right github url.
> Fixing repo url in master.

- versions.yaml
**What this PR does / why we need it**:  updated kdmp images required for latest stork
Closes #
> updated kdmp images required for latest stork

- charts/portworx/README.md
- charts/portworx/templates/storage-cluster.yaml
- charts/portworx/values.yaml
> PWX-34239 Add support for GKE

- charts/portworx/templates/storage-cluster.yaml
Fix volume mounts for PX on OKE
> PWX-34332 Fix volume mounts for PX on OKE

- charts/px-central/templates/px-backup/pxcentral-alertmanager.yaml
- charts/px-central/templates/px-backup/pxcentral-prometheus.yaml
- charts/px-central/values.yaml
**What this PR does / why we need it**: This PR has the changes to bring up prometheus and alerting stack w.r.t dashboard and alerting in px-backup 
Closes #
https://portworx.atlassian.net/browse/PB-4321
https://portworx.atlassian.net/browse/PB-4319
> Added initial changes to deploy prometheus and alertmanager

- charts/px-central/templates/px-backup/pxcentral-alertmanager.yaml
- charts/px-central/templates/px-backup/pxcentral-prometheus.yaml
**What this PR does / why we need it**: Added changes to fix config reloader to reflect alertmanagerconfig changes on alertmanager
Closes #
> Added changes to fix config reloader to reflect alertmanagerconfig changes on alertmanager

- charts/px-central/templates/px-backup/pxcentral-alertmanager.yaml
- charts/px-central/templates/px-backup/pxcentral-prometheus.yaml
**What this PR does / why we need it**: Fixed prometheus for basic_auth and added changes for ocp deployments
Closes # https://portworx.atlassian.net/browse/PB-5506
> PB-5506: Fixed prometheus for basic_auth and added changes for ocp deployments

- charts/px-central/templates/px-lighthouse/px-central-ui/pxcentral-lighthouse.yaml
Closes # https://portworx.atlassian.net/browse/PB-5630
> PB-5630: Added secrets access for middleware

- charts/px-central/templates/px-lighthouse/px-central-ui/pxcentral-ui.yaml
> PB-4536 added no referrer 

- charts/px-central/templates/px-lighthouse/px-central-ui/pxcentral-ui.yaml
> PB-5653 Keycloak endpoint should be changed to `/auth` instead of `/auth/`

- charts/px-central/templates/px-backup/pxcentral-alertmanager.yaml
- charts/px-central/templates/px-backup/pxcentral-backup.yaml
- charts/px-central/templates/px-backup/pxcentral-prometheus.yaml
- charts/px-central/templates/px-lighthouse/px-central-ui/pxcentral-lighthouse.yaml
- charts/px-central/templates/px-lighthouse/px-central-ui/pxcentral-ui.yaml
- charts/px-central/values.yaml
> Merging dashboard and alerting changes to 2.7.0

- charts/px-central/templates/px-backup/pxcentral-prometheus.yaml
- stable/index.yaml
**What this PR does / why we need it**:  Added changes to have more info on failure Alerts
Closes # https://portworx.atlassian.net/browse/PB-6148
> PB-6148: Added changes to have more info on failure Alerts

- charts/px-central/values.yaml
- versions.yaml
> PB-5669 keycloak login theme changes and busybox update

- charts/portworx/templates/storage-cluster.yaml
- charts/portworx/values.yaml
- test/portworx/storagecluster_helm_template_test.go
- test/portworx/testValues/storagecluster_all_components_enabled.yaml
- test/portworx/testValues/storagecluster_stork.yaml
- test/portworx/testspec/storagecluster_stork.yaml
Add missing fields in Stork component for helm.
Closes #https://purestorage.atlassian.net/browse/PWX-37568
> PWX-37588 | Add missing fields for stork

- charts/portworx/templates/storage-cluster.yaml
- charts/portworx/values.yaml
- test/portworx/storagecluster_helm_template_test.go
- test/portworx/testValues/storagecluster_nodeAffinity.yaml
- test/portworx/testspec/storagecluster_nodeAffinity.yaml
Add nodeAffinity in StorageCluster Placement rules in storageCluster template
Closes #https://purestorage.atlassian.net/browse/PWX-37685
> PWX-37685 | Add nodeAffinity in StorageCluster Placement rules

- charts/portworx/templates/storage-cluster.yaml
- charts/portworx/values.yaml
- test/portworx/storagecluster_helm_template_test.go
- test/portworx/testValues/storagecluster_nodes_configuration.yaml
- test/portworx/testspec/storagecluster_nodes_configuration.yaml
Added nodes specific configuration in storagecluster template.
Closes #https://purestorage.atlassian.net/browse/PWX-37686
> PWX-37686 |  Added nodes specific configuration 

- charts/px-central/templates/px-backup/pre-upgrade-hook/pre-upgrade-check.yaml
- charts/px-central/templates/px-lighthouse/pxcentral-post-install-hook.yaml
- charts/px-central/values.yaml
- versions.yaml
Reference PR: https://github.com/portworx/helm/pull/624
> PB-7463: Merge PB-7463 for pre-upgrade hook changes 

- charts/px-central/local_snapshot_restore.py
```
pb-8928: Added script for local snapshot restore.
More details on the usage of the script is present in the below runbook.
https://purestorage.atlassian.net/wiki/spaces/PE/pages/edit-v2/3743088916?draftShareId=f1584598-e798-4676-8409-47d9010140da&inEditorTemplatesPanel=auto_closed
```
Closes # pb-8928
Test result are available in the confluence page itself.
Test result with the updated code:
```
[core@pwx-ocp-0-167-9wcvn-worker-0-ptr99 ~]$ python3 1.py backup.json
+-------+-----------+------------+------------------------------------------+--------------------+
| Index | Namespace | PVC        | Name                                     | SnapshotID         | …
```
> pb-8928: Added script for local snapshot restore.

- charts/px-central/templates/px-backup/pre-install-hook/pre-install-check.yaml
- charts/px-central/templates/px-backup/pre-upgrade-hook/pre-upgrade-check.yaml
- charts/px-central/templates/px-backup/pxcentral-backup.yaml
- charts/px-central/templates/px-backup/pxcentral-mongodb.yaml
- charts/px-central/templates/px-lighthouse/px-central-oidc/pxcentral-keycloak.yaml
- charts/px-central/templates/px-lighthouse/px-central-ui/pxcentral-ui.yaml
- charts/px-central/values.yaml
**What this PR does / why we need it**: removes hardcoded mongo endpoint which has credentials
Closes # 
Successful install and upgrade
> PB-9641: Helm changes for password customisation

- charts/px-central/templates/_helpers.tpl
- charts/px-central/templates/px-backup/pre-install-hook/pre-install-check.yaml
- charts/px-central/templates/px-backup/pre-upgrade-hook/pre-upgrade-check.yaml
- charts/px-central/templates/px-backup/pxcentral-alertmanager.yaml
- charts/px-central/templates/px-backup/pxcentral-backup.yaml
- charts/px-central/templates/px-backup/pxcentral-mongodb.yaml
- charts/px-central/templates/px-backup/pxcentral-prometheus.yaml
- charts/px-central/templates/px-license-server/deployment.yaml
- charts/px-central/templates/px-lighthouse/px-central-oidc/pxcentral-keycloak.yaml
- charts/px-central/templates/px-lighthouse/px-central-ui/pxcentral-lighthouse.yaml
- charts/px-central/templates/px-lighthouse/px-central-ui/pxcentral-ui.yaml
- charts/px-central/templates/px-lighthouse/pxcentral-api-server.yaml
- charts/px-central/templates/px-lighthouse/pxcentral-post-install-hook.yaml
- charts/px-central/templates/px-monitor/cortex/cortex-backend.yaml
- charts/px-central/templates/px-monitor/cortex/cortex-sts.yaml
- charts/px-central/templates/px-monitor/cortex/cortex.yaml
- charts/px-central/templates/px-monitor/grafana/grafana.yaml
- charts/px-central/templates/px-monitor/prometheus/prometheus.yaml
- charts/px-central/values.yaml
**What this PR does / why we need it**: This PR adds the support for proxy configuration 
Introduces the below helm params
proxy.configSecretName
proxy.http
proxy.https
if proxy.configSecretName is not set , env values are updated directly . if its set, secret reference is added to the env values
Closes # https://purestorage.atlassian.net/browse/PB-10588
> PB-10588: Added changes to support proxy configurations

- charts/px-central/templates/_helpers.tpl
- charts/px-central/templates/px-backup/pre-install-hook/pre-install-check.yaml
- charts/px-central/templates/px-backup/pre-upgrade-hook/pre-upgrade-check.yaml
- charts/px-central/templates/px-backup/pxcentral-alertmanager.yaml
- charts/px-central/templates/px-backup/pxcentral-backup.yaml
- charts/px-central/templates/px-backup/pxcentral-mongodb.yaml
- charts/px-central/templates/px-backup/pxcentral-prometheus.yaml
- charts/px-central/templates/px-license-server/deployment.yaml
- charts/px-central/templates/px-lighthouse/px-central-oidc/pxcentral-keycloak.yaml
- charts/px-central/templates/px-lighthouse/px-central-ui/pxcentral-ui.yaml
- charts/px-central/templates/px-lighthouse/pxcentral-api-server.yaml
- charts/px-central/templates/px-lighthouse/pxcentral-post-install-hook.yaml
- charts/px-central/templates/px-monitor/cortex/cortex-backend.yaml
- charts/px-central/templates/px-monitor/cortex/cortex-sts.yaml
- charts/px-central/templates/px-monitor/cortex/cortex.yaml
- charts/px-central/templates/px-monitor/grafana/grafana.yaml
- charts/px-central/templates/px-monitor/prometheus/prometheus.yaml
> PB-10588: Added changes to support proxy configurations for missed central deploy/sts

- charts/px-central/templates/_helpers.tpl
- charts/px-central/templates/px-backup/pre-install-hook/pre-install-check.yaml
- charts/px-central/templates/px-backup/pre-upgrade-hook/pre-upgrade-check.yaml
- charts/px-central/templates/px-backup/pxcentral-alertmanager.yaml
- charts/px-central/templates/px-backup/pxcentral-backup.yaml
- charts/px-central/templates/px-backup/pxcentral-mongodb.yaml
- charts/px-central/templates/px-backup/pxcentral-prometheus.yaml
- charts/px-central/templates/px-license-server/deployment.yaml
- charts/px-central/templates/px-lighthouse/px-central-oidc/pxcentral-keycloak.yaml
- charts/px-central/templates/px-lighthouse/px-central-ui/pxcentral-lighthouse.yaml
- charts/px-central/templates/px-lighthouse/px-central-ui/pxcentral-ui.yaml
- charts/px-central/templates/px-lighthouse/pxcentral-api-server.yaml
- charts/px-central/templates/px-lighthouse/pxcentral-post-install-hook.yaml
- charts/px-central/templates/px-monitor/cortex/cortex-backend.yaml
- charts/px-central/templates/px-monitor/cortex/cortex-sts.yaml
- charts/px-central/templates/px-monitor/cortex/cortex.yaml
- charts/px-central/templates/px-monitor/grafana/grafana.yaml
- charts/px-central/templates/px-monitor/prometheus/prometheus.yaml
- charts/px-central/values.yaml
> Merge proxy feature changes to staging

- charts/portworx/templates/storage-cluster.yaml
- charts/portworx/values.yaml
- test/portworx/storagecluster_helm_template_test.go
- test/portworx/testspec/storagecluster_cert_manager_enabled.yaml
- test/portworx/testspec/storagecluster_internal_kvdb_tls_and_cert_manager.yaml
- test/portworx/testspec/storagecluster_internal_kvdb_tls_and_cert_manager_disabled.yaml
- test/portworx/testspec/storagecluster_internal_kvdb_tls_enabled.yaml
- test/portworx/testspec/storagecluster_migrate_to_kvdb_tls_enabled.yaml
What this PR does / why we need it:
This PR has the helm changes for KVDB TLS
Which issue(s) this PR fixes (optional)
Closes # PWX-43012
Special notes for your reviewer:
> PWX-43012: helm changes for kvdb tls

- charts/portworx/templates/storage-cluster.yaml
- charts/portworx/values.yaml
- test/portworx/storagecluster_helm_template_test.go
- test/portworx/testValues/storagecluster_with_workload_identity.yaml
- test/portworx/testspec/storagecluster_with_workload_identity.yaml
Adds helm changes for workload identity feature 
Closes #PWX-45407
> PWX-45407: Add helm changes for workload identity feature
